In [38]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [43]:
df = pd.read_csv('titanic_50000.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,1,Passenger_1,male,28.505531,4,1,TCKT84588,21.803954,NaN,S
1,2,1,1,Passenger_2,female,16.290422,0,3,TCKT87215,25.140471,NaN,S
2,3,0,3,Passenger_3,male,54.239256,3,4,TCKT56430,62.139033,NaN,S
3,4,0,3,Passenger_4,female,25.934960,1,2,TCKT97536,70.722917,C187,Q
4,5,0,3,Passenger_5,female,44.024119,2,3,TCKT56341,11.959749,NaN,S

In [44]:
df.isnull().sum()

PassengerId        0
Survived           0
Pclass             0
Name               0
Sex                0
Age                0
SibSp              0
Parch              0
Ticket             0
Fare               0
Cabin          34996
Embarked           0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  50000 non-null  int64
 1   Survived     50000 non-null  int64
 2   Pclass       50000 non-null  int64
 3   Name         50000 non-null  object
 4   Sex          50000 non-null  object
 5   Age          50000 non-null  float64
 6   SibSp        50000 non-null  int64
 7   Parch        50000 non-null  int64
 8   Ticket       50000 non-null  object
 9   Fare         50000 non-null  float64
 10  Cabin        15004 non-null  object
 11  Embarked     50000 non-null  object
dtypes: float64(2), int64(5), object(5)
memory usage: 4.6+ MB

In [47]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,0.499080,2.299300,30.094317,2.485500,2.493500,48.969638
std,14433.901067,0.500004,0.780161,13.788365,1.708581,1.704704,35.807589
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.003933
25%,12500.750000,0.000000,2.000000,20.589989,1.000000,1.000000,20.043044
50%,25000.500000,0.000000,2.000000,30.004980,2.000000,2.000000,42.437014
75%,37500.250000,1.000000,3.000000,39.458093,4.000000,4.000000,70.797499
max,50000.000000,1.000000,3.000000,80.000000,5.000000,5.000000,265.836314

In [48]:
df.shape

(50000, 12)

In [50]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,1,Passenger_1,male,28.505531,4,1,TCKT84588,21.803954,NaN,S
1,2,1,1,Passenger_2,female,16.290422,0,3,TCKT87215,25.140471,NaN,S
2,3,0,3,Passenger_3,male,54.239256,3,4,TCKT56430,62.139033,NaN,S
3,4,0,3,Passenger_4,female,25.934960,1,2,TCKT97536,70.722917,C187,Q
4,5,0,3,Passenger_5,female,44.024119,2,3,TCKT56341,11.959749,NaN,S